<?php
/**
 *------
 * BGA framework: © Gregory Isabelli <gisabelli@boardgamearena.com> & Emmanuel Colin <ecolin@boardgamearena.com>
 * fabiantest implementation : © Fabian Neumann <fabian.neumann@posteo.de>
 *
 * This code has been produced on the BGA studio platform for use on http://boardgamearena.com.
 * See http://en.boardgamearena.com/#!doc/Studio for more information.
 * -----
 *
 * material.inc.php
 *
 * fabiantest game material description
 *
 * Here, you can describe the material of your game with PHP variables.
 *
 * This file is loaded in your game logic class constructor, ie these variables
 * are available everywhere in your game logic code.
 *
 */

$this->constants = array(
  "EVIDENCE_DISPLAY_SIZE" => 9,
  "MINIGAMES" => 3,
  "DISCS_PER_PLAYER" => 3,
  "CUBES_PER_PLAYER" => 10,
);

// We use this as the basis to create all cards, evidence and base cards, but
// not all of the info is used in each deck. But as there is a 1:1 relation
// between cases and evidences, let's don't repeat ourselves.
$this->cardBasis = array(
  1 => array('name' => clienttranslate('Murder'),
             'nametr' => self::_('Murder'),
             'casetype' => 'crime',
            ),
  2 => array('name' => clienttranslate('Shorty'),
             'nametr' => self::_('Shorty'),
             'casetype' => 'suspect',
            ),
  3 => array('name' => clienttranslate('Doc'),
             'nametr' => self::_('Doc'),
             'casetype' => 'suspect',
            ),
  4 => array('name' => clienttranslate('Rusty'),
             'nametr' => self::_('Rusty'),
             'casetype' => 'suspect',
            ),
  5 => array('name' => clienttranslate('Bubbles'),
             'nametr' => self::_('Bubbles'),
             'casetype' => 'suspect',
            ),
  6 => array('name' => clienttranslate('Frenchy'),
             'nametr' => self::_('Frenchy'),
             'casetype' => 'suspect',
            ),
  7 => array('name' => clienttranslate('Maurice'),
             'nametr' => self::_('Maurice'),
             'casetype' => 'suspect',
            ),
  8 => array('name' => clienttranslate('Main Street'),
             'nametr' => self::_('Main Street'),
             'casetype' => 'location',
            ),
  9 => array('name' => clienttranslate('Waterfront'),
             'nametr' => self::_('Waterfront'),
             'casetype' => 'location',
            ),
  10 => array('name' => clienttranslate('Mob Killing'),
             'nametr' => self::_('Mob Killing'),
             'casetype' => 'crime',
            ),
  11 => array('name' => clienttranslate('Pop'),
             'nametr' => self::_('Pop'),
             'casetype' => 'suspect',
            ),
  12 => array('name' => clienttranslate('Dutch'),
             'nametr' => self::_('Dutch'),
             'casetype' => 'suspect',
            ),
  13 => array('name' => clienttranslate('Knuckles'),
             'nametr' => self::_('Knuckles'),
             'casetype' => 'suspect',
            ),
  14 => array('name' => clienttranslate('Pinky'),
             'nametr' => self::_('Pinky'),
             'casetype' => 'suspect',
            ),
  15 => array('name' => clienttranslate('Queenie'),
             'nametr' => self::_('Queenie'),
             'casetype' => 'suspect',
            ),
  16 => array('name' => clienttranslate('Earl'),
             'nametr' => self::_('Earl'),
             'casetype' => 'suspect',
            ),
  17 => array('name' => clienttranslate('Ocean Drive'),
             'nametr' => self::_('Ocean Drive'),
             'casetype' => 'location',
            ),
  18 => array('name' => clienttranslate('Union Square'),
             'nametr' => self::_('Union Square'),
             'casetype' => 'location',
            ),
  19 => array('name' => clienttranslate('Little Italy'),
             'nametr' => self::_('Little Italy'),
             'casetype' => 'location',
            ),
  20 => array('name' => clienttranslate('Bank Job'),
             'nametr' => self::_('Bank Job'),
             'casetype' => 'crime',
            ),
  21 => array('name' => clienttranslate('Blackmail'),
             'nametr' => self::_('Blackmail'),
             'casetype' => 'crime',
            ),
  22 => array('name' => clienttranslate('Police Corruption'),
             'nametr' => self::_('Police Corruption'),
             'casetype' => 'crime',
            ),
  23 => array('name' => clienttranslate('Forgery'),
             'nametr' => self::_('Forgery'),
             'casetype' => 'crime',
            ),
  24 => array('name' => clienttranslate('Downtown'),
             'nametr' => self::_('Downtown'),
             'casetype' => 'location',
            ),
  25 => array('name' => clienttranslate('China Town'),
             'nametr' => self::_('China Town'),
             'casetype' => 'location',
            ),
  26 => array('name' => clienttranslate('Forest Park'),
             'nametr' => self::_('Forest Park'),
             'casetype' => 'location',
            ),
  27 => array('name' => clienttranslate('Central Station'),
             'nametr' => self::_('Central Station'),
             'casetype' => 'location',
            ),
  28 => array('name' => clienttranslate('Rick’s Cafe'),
             'nametr' => self::_('Rick’s Cafe'),
             'casetype' => 'location',
            ),
  29 => array('name' => clienttranslate('Kidnapping'),
             'nametr' => self::_('Kidnapping'),
             'casetype' => 'crime',
            ),
  30 => array('name' => clienttranslate('Jewellery Heist'),
             'nametr' => self::_('Jewellery Heist'),
             'casetype' => 'crime',
            ),
  31 => array('name' => clienttranslate('Smuggling'),
             'nametr' => self::_('Smuggling'),
             'casetype' => 'crime',
            ),
  32 => array('name' => clienttranslate('Protection Racket'),
             'nametr' => self::_('Protection Racket'),
             'casetype' => 'crime',
            ),
  33 => array('name' => clienttranslate('Roadhouse'),
             'nametr' => self::_('Roadhouse'),
             'casetype' => 'location',
            ),
  34 => array('name' => clienttranslate('Trocadero'),
             'nametr' => self::_('Trocadero'),
             'casetype' => 'location',
            ),
  35 => array('name' => clienttranslate('Skid Row'),
             'nametr' => self::_('Skid Row'),
             'casetype' => 'location',
            ),
  36 => array('name' => clienttranslate('Lakeside'),
             'nametr' => self::_('Lakeside'),
             'casetype' => 'location',
            ),
);
